site_name: StackOne AI SDK
site_url: https://stackonehq.github.io/stackone-ai-python
repo_url: https://github.com/StackOneHQ/stackone-ai-python
repo_name: StackOneHQ/stackone-ai-python

docs_dir: .docs

theme:
  name: terminal
  palette: default
  features:
    - footer.prev_next
    - navigation.side.indexes
    - navigation.side.toc.hide
    - revision.date
    - revision.history
    - style.links.underline.hide

markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - .docs
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: lovelace
      noclasses: true
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Usage:
      - Getting Started: index.md
      - Error Handling: error-handling.md
      - File Uploads: file-uploads.md
      - Integrations:
        - OpenAI: openai-integration.md
