name: Dry Run Publish Package with pkg.pr.new

on:
  pull_request:
  push:

jobs:
  dry-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Install dependencies
        run: bun ci

      - name: ðŸš€ Dry Run Publish Package
        run: bun x pkg-pr-new publish
