name: Release Package
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-slim
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release-please
        with:
          release-type: node

  publish-package:
    runs-on: ubuntu-slim
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created  }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Setup Node.js for npm
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: ðŸ’« Install dependencies
        run: bun i

      - name: ðŸš€ Publish package
        run: npm publish --access public
        env:
          RELEASE: 1
