name: Release Package
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release-please
        with:
          release-type: node

  publish-package:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created  }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Setup Node.js for npm
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: ðŸ’« Install dependencies
        run: nix develop --command pnpm install --frozen-lockfile

      - name: ðŸš€ Publish package
        run: nix develop --command pnpm publish --access public --no-git-checks
